TOTAL_GROUND_LENGTH=121;
TOTAL_GROUND_WIDTH=84;

GROUND_HEIGHT=1;
FLOOR_HOLE_WIDTH=5;
FLOOR_HOLE_LENGTH=60;


//ground floor - holes
difference(){
 cube([TOTAL_GROUND_LENGTH,TOTAL_GROUND_WIDTH,GROUND_HEIGHT]);

 for( i= [15:15:TOTAL_GROUND_LENGTH-15]){
  translate([i,TOTAL_GROUND_WIDTH/2-FLOOR_HOLE_LENGTH/2,-1]){
   cube([FLOOR_HOLE_WIDTH,FLOOR_HOLE_LENGTH,GROUND_HEIGHT+2]);
  }
 }
}