:: Generic / Numbers
openscad -D num=2 -D "txt="""Advantage"" -o advantage.stl conditions.scad
openscad -D num=2 -D "txt="""Disadvantage"" -o disadvantage.stl conditions.scad
openscad -D num=2 -D "txt="""Concentrating"" -o concentrating.stl conditions.scad
openscad -D num=4 -D "txt="""1"" -o 1.stl conditions.scad
openscad -D num=4 -D "txt="""2"" -o 2.stl conditions.scad
openscad -D num=4 -D "txt="""3"" -o 3.stl conditions.scad
openscad -D num=4 -D "txt="""4"" -o 4.stl conditions.scad
openscad -D num=4 -D "txt="""5"" -o 5.stl conditions.scad
openscad -D num=4 -D "txt="""6"" -o 6.stl conditions.scad
openscad -D num=4 -D "txt="""7"" -o 7.stl conditions.scad
openscad -D num=4 -D "txt="""8"" -o 8.stl conditions.scad
openscad -D num=4 -D "txt="""9"" -o 9.stl conditions.scad
openscad -D num=4 -D "txt="""10"" -o 10.stl conditions.scad
openscad -D num=4 -D "txt="""A"" -o A.stl conditions.scad
openscad -D num=4 -D "txt="""B"" -o B.stl conditions.scad
openscad -D num=4 -D "txt="""C"" -o C.stl conditions.scad
openscad -D num=4 -D "txt="""D"" -o D.stl conditions.scad
openscad -D num=4 -D "txt="""E"" -o E.stl conditions.scad
openscad -D num=4 -D "txt="""F"" -o F.stl conditions.scad
openscad -D num=4 -D "txt="""G"" -o G.stl conditions.scad
openscad -D num=4 -D "txt="""H"" -o H.stl conditions.scad
openscad -D num=4 -D "txt="""I"" -o I.stl conditions.scad
openscad -D num=4 -D "txt="""J"" -o J.stl conditions.scad
openscad -D num=4 -D "txt="""K"" -o K.stl conditions.scad
openscad -D num=4 -D "txt="""L"" -o L.stl conditions.scad
openscad -D num=4 -D "txt="""M"" -o M.stl conditions.scad
openscad -D num=4 -D "txt="""N"" -o N.stl conditions.scad
openscad -D num=4 -D "txt="""O"" -o O.stl conditions.scad
openscad -D num=4 -D "txt="""P"" -o P.stl conditions.scad
openscad -D num=4 -D "txt="""Q"" -o Q.stl conditions.scad
openscad -D num=4 -D "txt="""R"" -o R.stl conditions.scad
openscad -D num=4 -D "txt="""S"" -o S.stl conditions.scad
openscad -D num=4 -D "txt="""T"" -o T.stl conditions.scad
openscad -D num=4 -D "txt="""U"" -o U.stl conditions.scad
openscad -D num=4 -D "txt="""V"" -o V.stl conditions.scad
openscad -D num=4 -D "txt="""W"" -o W.stl conditions.scad
openscad -D num=4 -D "txt="""X"" -o X.stl conditions.scad
openscad -D num=4 -D "txt="""Y"" -o Y.stl conditions.scad
openscad -D num=4 -D "txt="""Z"" -o Z.stl conditions.scad
